---
- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
  notify: Nginx enable

- name: Install certbot & RFC2136 plugin
  ansible.builtin.package:
    name:
      - certbot
      - python3-certbot-dns-rfc2136
    state: present

- name: Install rsync
  ansible.builtin.package:
    name: rsync
    state: present

- name: Install nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0774"
  notify: Nginx reload

- name: Copy RFC2136 credentials to Let's Encrypt directory
  ansible.builtin.template:
    src: rfc2136.ini.j2
    dest: "{{ nginx_tls_rfc2136_location }}"
    owner: root
    group: root
    mode: "0600"

- name: Provision TLS certificates for all configured domains
  ansible.builtin.command: >-
    /usr/bin/certbot
    --agree-tos
    --non-interactive
    --email {{ nginx_tls_email }}
    --dns-rfc2136
    --dns-rfc2136-credentials {{ nginx_tls_rfc2136_location }}
    --domains {{ nginx_tls_domains | join(",") | quote }}
    certonly
  args:
    creates: /etc/letsencrypt/live/{{ nginx_tls_domains[0] }}
  notify:
    - Nginx restart

- name: Copy HTPASSWD file
  ansible.builtin.copy:
    content: "{{ nginx_htpasswd }}"
    dest: /etc/nginx/htpasswd
    mode: "0600"
    owner: nginx
    group: nginx

- name: Generate nginx configurations
  ansible.builtin.template:
    src: nginx-site.j2
    dest: /etc/nginx/conf.d/{{ item.name }}
    mode: "0774"
  with_items:
    - "{{ nginx_sites }}"
  notify: Nginx reload

- name: Copy additional configurations
  ansible.builtin.copy:
    src: additional_configs/
    dest: /etc/nginx/conf.d/
    mode: "0774"
  notify: Nginx reload

- name: Reload nginx after certificate renewal
  ansible.builtin.copy:
    content: |
      #!/bin/sh
      set -ex

      systemctl reload nginx
    dest: /etc/letsencrypt/renewal-hooks/deploy/reload-nginx
    owner: root
    group: root
    mode: "0500"
