- hosts: all
  roles:
    - common
  tags:
    - common

- hosts: nameservers
  roles:
    - nameserver
  tags:
    - dns

- hosts: web
  roles:
    - nginx
  tags:
    - web

- hosts: web
  roles:
    - blog
  tags:
    - blog

- hosts: web
  roles:
    - gitea
  tags:
    - gitea
