---
- name: Deploy common services
  hosts: all
  roles:
    - common
  tags:
    - common

- name: Deploy nameservers to DNS hosts
  hosts: dns
  roles:
    - nameserver
  tags:
    - dns

- name: Deploy web software to webservers
  hosts: web
  roles:
    - nginx
  tags:
    - web
