all:
  hosts:
    core:
      ansible_host: core.host.jb3.dev
    rt1:
      ansible_host: rt1.host.jb3.dev
  children:
    routers:
      hosts:
        rt1:

    web:
      hosts:
        core:

    dns:
      hosts:
        core:
        rt1:

    tailscale:
      hosts:
        core:
        rt1:
