---
all:
  hosts:
    core:
      ansible_host: 202.61.228.148
    rt1:
      ansible_host: 66.245.193.219
  children:
    routers:
      hosts:
        rt1:
    web:
      hosts:
        core:
    dns:
      hosts:
        core:
        rt1:
    tailscale:
      hosts:
        core:
        rt1:
    tor:
      hosts:
        core:
  vars:
    primary_nameserver: core
    tor_address: joebanksukvuobm4ko4zsujdqydeuza5olorgmokpjcxqcr6gctu7vqd.onion
