---
tls_email: joe@jb3.dev
tls_well_known_location: /usr/share/nginx/letsencrypt

sites:
  - name: default
    type: static
    domain: jb3.dev
    root: /usr/share/nginx/jb3.dev
  - name: matrix
    type: reverse-proxy
    domain: matrix.jb3.dev
    upstream: http://localhost:8008
    additional_ports:
      - port: 8448
        tls: true
  - name: znc
    type: reverse-proxy
    domain: znc.jb3.dev
    upstream: https://localhost:1500
