sites:
- name: modmail
  type: reverse-proxy
  certificate: jb3.dev
  domain: modmail.jb3.dev
  upstream: http://localhost:8890
- name: default
  certificate: jb3.dev
  type: static
  domain: jb3.dev
  root: /var/www/jb3.dev
