- name: named enable
  service:
    name: named
    enabled: yes
    state: started

- name: named update
  service:
    name: named
    state: reloaded

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
