- name: bind enable
  service:
    name: bind9
    enabled: yes
    state: started

- name: bind update
  service:
    name: bind9
    state: reloaded

- name: disable named apparmor
  command: apparmor_parser -R /etc/apparmor.d/usr.sbin.named
  when: apparmor_disable.changed

- name: stop bind
  command: rndc stop
  listen: bind update
