---
- name: Named enable
  ansible.builtin.service:
    name: named
    enabled: true
    state: started

- name: Named update
  ansible.builtin.service:
    name: named
    state: reloaded

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
