---
- name: Restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted
    enabled: true
