---
nginx_tls_email: joe@jb3.dev
nginx_tls_well_known_location: /usr/share/nginx/letsencrypt

nginx_sites:
  - name: default
    type: static
    domain: jb3.dev
    root: /usr/share/nginx/jb3.dev
  - name: matrix
    type: reverse-proxy
    domain: matrix.jb3.dev
    upstream: http://localhost:8008
    additional_ports:
      - port: 8448
        tls: true
  - name: znc
    type: reverse-proxy
    domain: znc.jb3.dev
    upstream: https://localhost:1500
  - name: leacs
    type: static
    domain: leacs.jb3.dev
    root: /usr/share/nginx/leacs
    authenticated: true
