---
name: Lint Playbook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible Lint
        run: pip install ansible-lint

      - name: Run ansible lint
        run: |
          # Remove any Vaulted files and Vault configuration
          grep -R '$ANSIBLE_VAULT;' --files-with-matches . | xargs rm
          sed --in-place '/vault_password_file/d' ansible.cfg
          ansible-lint
